apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orleans-urlshortener
  namespace: orleans-urlshortener
  labels:
    app: orleans-urlshortener
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: orleans-urlshortener
