apiVersion: v1
kind: ServiceAccount
metadata:
  name: orleans-urlshortener
  namespace: orleans-urlshortener
  labels:
    app: orleans-urlshortener
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orleans-urlshortener
  namespace: orleans-urlshortener
  labels:
    app: orleans-urlshortener
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orleans-urlshortener
  namespace: orleans-urlshortener
  labels:
    app: orleans-urlshortener
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orleans-urlshortener
subjects:
- kind: ServiceAccount
  name: orleans-urlshortener
  namespace: orleans-urlshortener
